### ISSUE TITLE
Documentation deployment

### ISSUE THREAD

**Issue by m-albert** [multiview-stitcher/multiview-stitcher#1]
Let's get automated documentation deployment working.

**Comment by m-albert** [comment]
The repository is public now!

**Comment by alexschroeter** [comment]
I have created a bit of a concept for the documentation and started a PR (https://github.com/multiview-stitcher/multiview-stitcher/pull/2). Let me know what you think.

**Comment by m-albert** [comment]
Discussion follow up is in #2.
