### ISSUE TITLE
reademe.md is not clear enough

### ISSUE THREAD

**Issue by lv-shi-long** [multiview-stitcher/multiview-stitcher#14]
so how to run it?

**Comment by alexschroeter** [comment]
I appreciate your interest in the project. Please be aware that the project is being developed in the open but has not been released yet. That said the README has all the necessary steps to install and the [notebooks folder](https://github.com/multiview-stitcher/multiview-stitcher/tree/main/notebooks) has some example use cases. If you are having trouble getting set up please let us know what you are struggling with (best list your steps) so we can improve the documentation where things are missing or unclear.

Cheers, Alex

**Comment by m-albert** [comment]
@lv-shi-long

As @alexschroeter mentioned, the notebooks are currently the best entry point. For what it's worth, I've added a mention to them in the README. Thanks for pointing this out and feel free to create issues with any problems you should run into.
