### ISSUE TITLE
Make ipympl dependency optional?

### ISSUE THREAD

**Issue by dpshepherd** [multiview-stitcher/multiview-stitcher#15]
Hi @m-albert!

I hope you are well. We are going to give your new stitching project a try. However, adding the ipympl dependency makes it a somewhat heavyweight installation because of iPython, Jupyter, etc...

Would it be possible to make that optional for examples or testing? Alternatively, we can fork and remove the dependence.

Thanks,
Doug

**Comment by m-albert** [comment]
Hi @dpshepherd, thanks for writing here!

I think you're completely right that `ipympl` (also `jupyter` for that matter) shouldn't be part of the install requirements. I've removed `ipympl` completely and moved `jupyter` to the testing extras, where it's needed for testing the example notebooks. Thanks for pointing this out!

**Comment by m-albert** [comment]
I guess you've seen that the repository is under development and there hasn't been a release yet, so please keep in mind that things will change and mature and functionality is still very limited. With that in mind, I'm very happy to help out with anything if needed and to quickly incorporate feedback you might have!

**Comment by dpshepherd** [comment]
> I guess you've seen that the repository is under development and there hasn't been a release yet, so please keep in mind that things will change and mature and functionality is still very limited. With that in mind, I'm very happy to help out with anything if needed and to quickly incorporate feedback you might have!

Yup! We wanted to test it out for stitching 3D epifluorescence images acquired in a grid as part of a much larger project. Thanks for the change, we are getting our data into the right format and should have the initial trial done this week.
