### ISSUE TITLE
Fused image black everywhere except for the first image

### ISSUE THREAD

**Issue by ashkan-mokarian** [multiview-stitcher/multiview-stitcher#20]
By following the steps in 'notebooks/stitching_bigstitcher_grid_2d.ipynb', the code correctly finds correct registration parameters and shows **correct** results in napari viewer. After following with the fusion part of the code, even though everything runs smoothly and without any errors, the resulting image is incorrect. The output shape of the stitched image is correct, but the values are everywhere 0 except for the most top left image (index 0).

Here is the final image from the fusion:
![Grid_fused](https://github.com/multiview-stitcher/multiview-stitcher/assets/2429939/eced7a4f-e983-4023-8311-62a4533ebc96)

**Comment by m-albert** [comment]
Hi @ashkan-mokarian, thanks for posting this issue!

There had been a problem with the fusion in a previous release, which should however be fixed. Which version of `multiview-stitcher` are you using? When running the notebook with 0.1.5 (released just now) the fusion looks good. Please don't hesitate to write back here if the problem persists with 0.1.5.

**Comment by ashkan-mokarian** [comment]
Thanks for your quick reply.

After updating the package to 0.1.5, the problem was resolved.
